---

- hosts: pga
  tags: dev-seagrid
  vars:
      portal_dir: "{{portals_dir}}/dev-seagrid"
  roles:
      - pga

- hosts: pga
  tags: dev-scigap
  vars:
      portal_dir: "{{portals_dir}}/dev-scigap"
  roles:
      - pga