---

# API Server deployment
- hosts: dev-airavata
  vars:
      airavata_source_dir: "/home/airavata/dev-airavata-source"
      airavata_repo: "https://git-wip-us.apache.org/repos/asf/airavata.git"
      git_branch: "develop"
      do_git_pull: true
      deployment_dir: "/home/airavata/dev-deployment/api-orch"
      server_name: "api-orch"
  roles:
      - airavata_deploy