
- name: server start file
  find: paths={{ local_airavata_dir }}/apache-airavata-server-0.17-SNAPSHOT/bin/ patterns="server_start_*"
  register: server_start_file
  listen: "restart airavata"

- name: stop the server
  shell: "{{ local_airavata_dir }}/apache-airavata-server-0.17-SNAPSHOT/bin/airavata-server-stop.sh"
  register: stop_airavata
  listen: "restart airavata"
  ignore_errors: True
  when: server_start_file.matched == 1

- name: force stop the server
  shell: "{{ local_airavata_dir }}/apache-airavata-server-0.17-SNAPSHOT/bin/airavata-server-stop.sh -f"
  listen: "restart airavata"
  when: stop_airavata|failed

- name: start the server
  shell: "{{ local_airavata_dir }}/apache-airavata-server-0.17-SNAPSHOT/bin/airavata-server-start.sh -d all"
  listen: "restart airavata"
